const SYSTEM_ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  MANAGEMENT: "MANAGEMENT",
  AREA_MANAGER: "AREA_MANAGER",
  PROFESSIONAL: "PROFESSIONAL",
  ASSISTANT: "ASSISTANT"
};

const SYSTEM_PERMISSIONS = {
  USERS_MANAGE: "users.manage",
  COMPANIES_MANAGE: "companies.manage",
  COMPANIES_VIEW: "companies.view",
  COMPANIES_CREATE: "companies.create",
  COMPANIES_EDIT: "companies.edit",
  COMPANIES_DELETE: "companies.delete",
  TAXES_MANAGE: "taxes.manage",
  TASKS_MANAGE: "tasks.manage",
  TASKS_VIEW: "tasks.view",
  TASKS_CREATE: "tasks.create",
  TASKS_EDIT: "tasks.edit",
  TASKS_DELETE: "tasks.delete",
  TASKS_ASSIGN: "tasks.assign",
  DASHBOARD_VIEW: "dashboard.view",
  SETTINGS_MANAGE: "settings.manage",
  REPORTS_VIEW: "reports.view",
  REPORTS_EXPORT: "reports.export",
  AUDIT_VIEW: "audit.view"
};

const DEFAULT_ROLE_PERMISSIONS = {
  [SYSTEM_ROLES.SUPER_ADMIN]: Object.values(SYSTEM_PERMISSIONS),
  [SYSTEM_ROLES.MANAGEMENT]: [
    SYSTEM_PERMISSIONS.COMPANIES_VIEW,
    SYSTEM_PERMISSIONS.TASKS_VIEW,
    SYSTEM_PERMISSIONS.DASHBOARD_VIEW,
    SYSTEM_PERMISSIONS.REPORTS_VIEW,
    SYSTEM_PERMISSIONS.REPORTS_EXPORT,
    SYSTEM_PERMISSIONS.AUDIT_VIEW
  ],
  [SYSTEM_ROLES.AREA_MANAGER]: [
    SYSTEM_PERMISSIONS.COMPANIES_MANAGE,
    SYSTEM_PERMISSIONS.COMPANIES_VIEW,
    SYSTEM_PERMISSIONS.COMPANIES_CREATE,
    SYSTEM_PERMISSIONS.COMPANIES_EDIT,
    SYSTEM_PERMISSIONS.COMPANIES_DELETE,
    SYSTEM_PERMISSIONS.TAXES_MANAGE,
    SYSTEM_PERMISSIONS.TASKS_MANAGE,
    SYSTEM_PERMISSIONS.TASKS_VIEW,
    SYSTEM_PERMISSIONS.TASKS_CREATE,
    SYSTEM_PERMISSIONS.TASKS_EDIT,
    SYSTEM_PERMISSIONS.TASKS_DELETE,
    SYSTEM_PERMISSIONS.TASKS_ASSIGN,
    SYSTEM_PERMISSIONS.DASHBOARD_VIEW,
    SYSTEM_PERMISSIONS.REPORTS_VIEW,
    SYSTEM_PERMISSIONS.REPORTS_EXPORT
  ],
  [SYSTEM_ROLES.PROFESSIONAL]: [
    SYSTEM_PERMISSIONS.COMPANIES_VIEW,
    SYSTEM_PERMISSIONS.TASKS_MANAGE,
    SYSTEM_PERMISSIONS.TASKS_VIEW,
    SYSTEM_PERMISSIONS.TASKS_EDIT,
    SYSTEM_PERMISSIONS.TAXES_MANAGE,
    SYSTEM_PERMISSIONS.DASHBOARD_VIEW
  ],
  [SYSTEM_ROLES.ASSISTANT]: [
    SYSTEM_PERMISSIONS.COMPANIES_VIEW,
    SYSTEM_PERMISSIONS.TASKS_MANAGE,
    SYSTEM_PERMISSIONS.TASKS_VIEW
  ]
};

module.exports = {
  SYSTEM_ROLES,
  SYSTEM_PERMISSIONS,
  DEFAULT_ROLE_PERMISSIONS
};
